# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from ceramicraft_product_agent.grpc_client import product_pb2 as product__pb2

GRPC_GENERATED_VERSION = "1.78.0"


class ProductServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateStockWithCAS = channel.unary_unary(
            "/productpb.ProductService/UpdateStockWithCAS",
            request_serializer=product__pb2.UpdateStockWithCASRequest.SerializeToString,
            response_deserializer=product__pb2.UpdateStockWithCASResponse.FromString,
            _registered_method=True,
        )
        self.GetProductList = channel.unary_unary(
            "/productpb.ProductService/GetProductList",
            request_serializer=product__pb2.GetProductListRequest.SerializeToString,
            response_deserializer=product__pb2.GetProductListResponse.FromString,
            _registered_method=True,
        )
        self.CreateProduct = channel.unary_unary(
            "/productpb.ProductService/CreateProduct",
            request_serializer=product__pb2.CreateProductRequest.SerializeToString,
            response_deserializer=product__pb2.CreateProductResponse.FromString,
            _registered_method=True,
        )


class ProductServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateStockWithCAS(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetProductList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "UpdateStockWithCAS": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateStockWithCAS,
            request_deserializer=product__pb2.UpdateStockWithCASRequest.FromString,
            response_serializer=product__pb2.UpdateStockWithCASResponse.SerializeToString,
        ),
        "GetProductList": grpc.unary_unary_rpc_method_handler(
            servicer.GetProductList,
            request_deserializer=product__pb2.GetProductListRequest.FromString,
            response_serializer=product__pb2.GetProductListResponse.SerializeToString,
        ),
        "CreateProduct": grpc.unary_unary_rpc_method_handler(
            servicer.CreateProduct,
            request_deserializer=product__pb2.CreateProductRequest.FromString,
            response_serializer=product__pb2.CreateProductResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "productpb.ProductService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "productpb.ProductService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ProductService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateStockWithCAS(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/productpb.ProductService/UpdateStockWithCAS",
            product__pb2.UpdateStockWithCASRequest.SerializeToString,
            product__pb2.UpdateStockWithCASResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetProductList(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/productpb.ProductService/GetProductList",
            product__pb2.GetProductListRequest.SerializeToString,
            product__pb2.GetProductListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateProduct(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/productpb.ProductService/CreateProduct",
            product__pb2.CreateProductRequest.SerializeToString,
            product__pb2.CreateProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
